[package]
name = "codeslide-cli"
version = "0.6.1"
edition = "2021"

[[bin]]
name = "codeslide-cli"
path = "./src/cli/main.rs"

[dependencies]
askama = { version = "0.12.0", features = ["serde-json"] }
if_chain = "1.0.2"
indexmap = { version = "1.9.3", features = ["serde-1", "std"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
