[package]
name = "codeslide-cli"
version = "0.3.4"
edition = "2021"

[[bin]]
name = "codeslide-cli"
path = "./src/cli/main.rs"

[dependencies]
askama = "0.12.0"
indexmap = { version = "1.9.3", features = ["serde-1"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
